### ISSUE TITLE
Nucleotide length in reference .gb file

### ISSUE THREAD

**Issue by trvrb** [seattleflu/augur-build#16]
@cassiawag ---

One more small fix to the `create_ref_genome.gb` function. The current file looks like:
```
FEATURES             Location/Qualifiers
     source          1..1701
                     /mol_type="genomic RNA"
```
This `1701` references to the total length of the nucleotide sequence in the Genbank file. This should be `13350` instead. 

This is a small fix and there's no rush.

**Comment by cassiawag** [comment]
Can do.

**Comment by cassiawag** [comment]
It looks like there was an individual source for each of the segments, and they all were preserved and added to the features, so there's 8 sources in the final Genbank file. Do you want me to modify the script, so there's only one source for the entire full-genome Genbank file, @trvrb ?

**Comment by trvrb** [comment]
Yes. Please just keep the single `source` at the top of the `FEATURES` block. Remove others. Adjust `source` to match entire genome length, ie `1..13350`.
