### ISSUE TITLE
Include script to hide ancestral nodes based on cluster designation

### ISSUE THREAD

**Issue by trvrb** [seattleflu/augur-build#19]
@jameshadfield ---

Currently, clustering across segments proceeds as:

1. Identify genomic constellations / clusters via `connected_components.py` and add `cluster` label to each tip via its node data output (rule `clustering`)
2. Make a genome FASTA file for each `cluster` (rule `clusters_fasta`)
3. Align each cluster with `augur align` (rule `align_clusters`)
4. Build tree for each cluster with `augur tree` (rule `tree_clusters`)
5. Reroot each of these trees to output `augur refine` (rule `refine_clusters`)
6. Switch individual rooted cluster trees together with a basal polytomy (rule `aggregate_cluster_trees`)
7. Run `augur refine` to estimate timetree, but keep topology fixed (rule `refine_aggregated`)

The output here is then a single tree where each `cluster` forms a monophyletic clade. I believe the only remaining thing we need here is a script to "hide" nodes basal to each of these monophyletic cluster clades. I imagine this works as follows:

Take as input:
* the output of (7), eg `results/aggregated/tree_h3n2_genome_2y.nwk`
* the output of (1) cluster labeling node data, eg `results/clustering_h3n2_2y.json`

Output:
* node data JSON the specifies basal nodes as `hidden`, eg `results/aggregated/mask_h3n2_genome_2y.json`.

Then this "mask" would be handed to `export_aggregated` to result in an exploded auspice JSON. Does this seem like a reasonable approach?

**Comment by jameshadfield** [comment]
@trvrb I've implemented this as a post-`augur export` step. (In augur v6, `augur export` will be able to do this, but I think we want SFS to run on augur v5.)

Steps needed for the snakefile:
(1) rule `export_aggregated` should save the tree JSON into "./results", (the meta JSON should be saved in "./auspice" as it is currently.
(2):

```
python scripts/annotate_hidden_nodes.py \
    --input results/seattle_flu_seasonal_h3n2_genome_2y_tree.json \
    --output auspice/seattle_flu_seasonal_h3n2_genome_2y_tree.json 
```

This script has the side effect of labeling internal nodes with the cluster (previously only terminal nodes).

![image](https://user-images.githubusercontent.com/8350992/61190681-6cda7d00-a6f4-11e9-89b9-3b20cfbf3c8f.png)

**Comment by jameshadfield** [comment]
Branch [exploded](https://github.com/seattleflu/augur-build/tree/exploded) Now modified to remove the trailing branch & maximize what's shown in auspice -- see https://github.com/seattleflu/augur-build/commit/cef2d75772f1f710474d0330ac4ef60df93fa600 for more info.

temporal view:
![image](https://user-images.githubusercontent.com/8350992/61191599-7833a580-a700-11e9-9cad-c4121ed0a1bf.png)

divergence:
![image](https://user-images.githubusercontent.com/8350992/61191603-8255a400-a700-11e9-9547-749994299412.png)

**Comment by jameshadfield** [comment]
@trvrb if you modify https://github.com/seattleflu/augur-build/blob/exploded/scripts/annotate_hidden_nodes.py#L53 to be, e.g.
```
        "attr": {
            "num_date": node["attr"]["num_date"] - 1/12,
            "div": node["attr"]["div"] - 0.0002
        },
```
Then you'll have little stubs which you can click on to zoom into each cluster, like so:

![image](https://user-images.githubusercontent.com/8350992/61191724-d4e39000-a701-11e9-994d-633fdaffc5e2.png)

**Comment by trvrb** [comment]
Thanks @jameshadfield! This is great.
